### PR TITLE
fix: discard intermediate proofs

### LINKED ISSUE #104: Do not persist all intermediary block proofs to disk
Since #96, we have the ability to prove a sequence of blocks in one go. This however writes all generated block proofs to disk, which is not needed.
More specifically, say we have checkpoint height $N$ and we generate blocks $N+1$ to $M$, then every subsequent proof $\pi_t$ will be attesting validity of all previous block proofs $pi_{N < i < t}$. As such, only the latter is really useful and needs to be persisted.

### PR DESCRIPTION
**Pull request by atanmarko**
Resolves https://github.com/0xPolygonZero/zero-bin/issues/104

### CODE REVIEW

File: leader/src/jerigon.rs [hunk 1]
```diff
@@ -27,21 +27,24 @@ pub(crate) async fn jerigon_main(
     )
     .await?;
 
-    let block_proofs = prover_input
+    // We keep only last block proof from the interval. It contains
+    // all the necessary information to verify the whole interval.
```
Comment (Nashtare) [inline leader/src/jerigon.rs]:
```suggestion
    // We keep only the last block proof from the interval. It contains
    // all the necessary information to verify the whole sequence.
```

File: leader/src/jerigon.rs [hunk 2]
```diff
@@ -27,21 +27,24 @@ pub(crate) async fn jerigon_main(
...
+    let last_block_proof = prover_input
         .prove(&runtime, previous_proof, save_inputs_on_error)
```
Comment (Nashtare) [inline leader/src/jerigon.rs]: **design question**: we may want to store / flush intermediate proofs on the go, in case the program aborts for some reasons, so that we don't restart everything from scratch? I don't think the extra I/O would be prohibitive.

File: leader/src/jerigon.rs [hunk 3]
```diff
@@ -27,21 +27,24 @@ pub(crate) async fn jerigon_main(
...
-        )?;
-    }
+    let last_block_proof_serialized = serde_json::to_vec(&last_block_proof)?;
+    write_proof(
+        last_block_proof_serialized,
+        proof_output_dir_opt.clone().map(|mut path| {
+            path.push(format!("b{}.zkproof", last_block_proof.b_height));
+            path
+        }),
+    )?;
```
Comment (Nashtare) [inline leader/src/jerigon.rs]: Partly related to the design question above, if we go in this direction, then we _may_ want to flush the previous proof passed as arg as well (up to the user). Could be configurable ideally.

File: leader/src/jerigon.rs (hunk 2 above)
Comment (atanmarko) [reply leader/src/jerigon.rs]: We need to change logic then and store them the moment they are generated, at the moment all the proofs are collected first and then stored

File: leader/src/jerigon.rs (hunk 3 above)
Comment (atanmarko) [reply leader/src/jerigon.rs]: Yes, I had the same idea. Will update accordingly

File: tools/prove_blocks.sh [hunk 4]
```diff
@@ -81,7 +81,7 @@ fi
 if [[ $5 == "test_only" ]]; then
     # test only run
     echo "Proving blocks ${BLOCK_INTERVAL} in a test_only mode now... (Total: ${TOT_BLOCKS})"
-    cargo r --release --features test_only --bin leader -- --runtime in-memory --load-strategy on-demand jerigon --rpc-url "$NODE_RPC_URL" --block-interval $BLOCK_INTERVAL --proof-output-dir $PROOF_OUTPUT_DIR $PREV_PROOF_EXTRA_ARG > $OUT_LOG_PATH 2>&1
+    cargo r --release --features test_only --bin leader -- --runtime in-memory --load-strategy on-demand jerigon --rpc-url "$NODE_RPC_URL" --block-interval $BLOCK_INTERVAL --proof-output-dir $PROOF_OUTPUT_DIR $PREV_PROOF_EXTRA_ARG 2>&1 > $OUT_LOG_PATH
```
Comment (Nashtare) [inline tools/prove_blocks.sh]: Is it actually changing anything? I see it as still redirecting `stdout` and `stderr` to `$OUT_LOG_PATH`, similarly to calling `&> $OUT_LOG_PATH` directly.

File: leader/src/jerigon.rs [hunk 5]
```diff
@@ -1,61 +1,64 @@
...
+use tracing::{error, info};
+
+#[derive(Debug, Default)]
+pub(crate) struct JerigonParams {
+    pub checkpoint_block_number: u64,
+    pub previous_proof: Option<GeneratedBlockProof>,
+    pub proof_output_dir: Option<PathBuf>,
+    pub save_inputs_on_error: bool,
+    pub keep_intermediate_proofs: bool,
+}
```
Comment (Nashtare) [inline leader/src/jerigon.rs]: minor: may deserve to live outside of `jerigon.rs` as this would also be used with the `native` tracer (whichever gets merged first into `develop`), and be renamed to `ProofParams` or something else more neutral.

File: leader/src/jerigon.rs [hunk 6]
```diff
@@ -1,61 +1,64 @@
...
-    Ok(())
-}
-
-fn write_proof(proof: Vec<u8>, proof_output_dir_opt: Option<PathBuf>) -> Result<()> {
-    match proof_output_dir_opt {
-        Some(p) => {
-            if let Some(parent) = p.parent() {
-                create_dir_all(parent)?;
-            }
+    info!("Proved blocks: {proved_blocks:?}");
```
Comment (Nashtare) [inline leader/src/jerigon.rs]: nit: to be removed

File: leader/src/jerigon.rs [hunk 7]
```diff
@@ -1,61 +1,64 @@
...
 
-            let mut f = File::create(p)?;
-            f.write_all(&proof)?;
+    if !params.keep_intermediate_proofs {
+        if let Some(proof_output_dir) = params.proof_output_dir.as_ref() {
```
Comment (Nashtare) [inline leader/src/jerigon.rs]: minor: maybe a `warn!` message if `params.proof_output_dir` is `None`, given that we want to remove non-existing intermediate proofs.

File: tools/prove_blocks.sh (hunk 4 above)
Comment (atanmarko) [reply tools/prove_blocks.sh]: I was actually paranoid as I didn't see some output. Will revert it

File: leader/src/jerigon.rs [hunk 8]
```diff
@@ -1,61 +1,64 @@
...
+            .rev()
+            .skip(1)
+            .map(|b| generate_block_proof_file_name(&proof_output_dir.to_str(), b))
+            .for_each(|path| {
+                if let Err(e) = std::fs::remove_file(path) {
+                    error!("Failed to remove intermediate proof file: {e}");
+                }
+            });
+    } else {
+        // Proofs are written to stdio, so no need to clean up
```
Comment (Nashtare) [inline leader/src/jerigon.rs:61]:
```suggestion
        // Proofs are written to stdout, so no need to clean up
```

**Review by Nashtare — APPROVED** [review]
LGTM. I can't test it as I don't have any Jerigon node endpoint atm, but I trust you did :)

File: leader/src/jerigon.rs (hunk 8 above)
Comment (atanmarko) [reply leader/src/jerigon.rs:61]: Fixed in #109
